<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://example.com/QAjuda"
             targetNamespace="http://example.com/QAjuda">

  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://example.com/QAjuda">

      <element name="vezesDoisRequest">
        <complexType>
          <sequence>
            <element name="input" type="xsd:double"/>
          </sequence>
        </complexType>
      </element>

      <element name="vezesDoisResponse">
        <complexType>
          <sequence>
            <element name="output" type="xsd:double"/>
          </sequence>
        </complexType>
      </element>

    </schema>
  </types>

  <message name="vezesDoisRequest">
    <part name="parameters" element="tns:vezesDoisRequest"/>
  </message>

  <message name="vezesDoisResponse">
    <part name="parameters" element="tns:vezesDoisResponse"/>
  </message>

  <portType name="QAjudaPortType">
    <operation name="vezesDois">
      <input message="tns:vezesDoisRequest"/>
      <output message="tns:vezesDoisResponse"/>
    </operation>
  </portType>

  <binding name="QAjudaBinding" type="tns:QAjudaPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

    <operation name="vezesDois">
      <soap:operation style="document" soapAction="http://example.com/QAjuda#vezesDois"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>

  </binding>

  <service name="QAjudaService">
    <port name="QAjudaPort" binding="tns:QAjudaBinding">
      <soap:address location="http://localhost:8000/QAjuda"/>
    </port>
  </service>

</definitions>
